import { ArrowUpRight, BellRing, Link2, Radio, Terminal } from 'lucide-react';
const commands=[['/link','Connect your Riot ID to your Discord account in a server.'],['/setchannel','Choose the announcement channel. Requires server permissions.'],['/tracking','Enable or disable your match notifications.'],['/live','Request current match information.'],['/activity','Check the Discord activity detected by the bot.'],['/unlink','Remove your account link for this server.']];
export default function About(){return <>
<div className="page-heading"><div><div className="eyebrow">THE DISCORD BOT</div><h1>Your next match.<br/>Your server, in the loop.</h1><p>LeagueMatch announces linked players’ League of Legends matches<br className="desktop"/> and is developing historical matchup insights.</p></div></div>
<div className="about-intro"><div><span className="badge">PROTOTYPE</span><h2>Built around your community.</h2><p>Server admins choose an announcement channel. Players link a Riot ID and control their own tracking preference. LeagueMatch checks activity and sends a match announcement when a new game is detected.</p><a className="button primary" href="https://github.com/ReymondOH/LeagueMatch-Discord-Bot" target="_blank" rel="noreferrer">View source and request test access <ArrowUpRight size={17}/></a></div><div className="discord-example"><div className="discord-channel"># league-matches <span>Illustrative example</span></div><div className="discord-body"><div className="bot-avatar">LM</div><div><strong>LeagueMatch <span className="bot-label">APP</span></strong><div className="embed"><span className="eyebrow">MATCH FOUND</span><h3>Player#TAG is in a match</h3><p>Champion and match details appear here<br/>in the server’s chosen channel.</p><small>Example message · not a live player</small></div></div></div></div></div>
<div className="section-title"><h2>How it works</h2><p>Account linking happens in Discord.</p></div><div className="three-grid">{[{Icon:Link2,n:'01',title:'Link your account',copy:'Run /link with your Riot game name and tag line. The bot stores the link for that Discord server.'},{Icon:Radio,n:'02',title:'Detect a match',copy:'With tracking enabled, the bot checks for a current game when Discord shows you playing League.'},{Icon:BellRing,n:'03',title:'Notify your server',copy:'The bot posts to the selected channel and remembers the game ID to avoid duplicate announcements.'}].map(({Icon,n,title,copy})=><article className="note-card" key={n}><div className="step-top"><Icon size={23}/><span>{n}</span></div><h3>{title}</h3><p>{copy}</p></article>)}</div>
<div className="section-title"><h2>Commands you can use</h2><p>The current bot command set.</p></div><section className="panel command-list">{commands.map(([command,description])=><div key={command}><code><Terminal size={16}/>{command}</code><p>{description}</p></div>)}</section>
<div className="below-grid"><article className="note-card"><span className="eyebrow">CURRENT</span><h3>Match tracking and collection</h3><p>The Python bot links accounts, announces matches, and collects ranked solo results in PostgreSQL. This React dashboard can show aggregate results through a separate FastAPI service.</p></article><article className="note-card"><span className="eyebrow">PLANNED</span><h3>Deeper historical insights</h3><p>Rune and summoner-spell breakdowns with sample sizes, and post-match analysis. A match score is still experimental and is not implemented in this dashboard.</p></article></div>
</>}
